# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tv1
    value: tv1SuperSecretVal

steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    goals: 'clean install'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.11'
#    mavenVersionOption: 'Default'
#    mavenOptions: '-Xmx3072m'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

# - task: FortifyOnDemandStatic@6
#   inputs:
#     FortifyProjects: './'
#     ReleaseId: 248097
#     FodConnection: 'FoD Service Connection'
#     EntitlementPreference: '0'
#     InProgressScanActionType: '2'
#     RemediationScanPreference: '0'
#     PolicyFailAction: '0'

- task: CmdLine@2
  inputs:
    script: |
      echo "SC Client Secret: $(ScanCentral.ClientToken)"
      echo "SSC Token: " $(ScanCentral.SscCiToken)
      echo "Test var 1: $(tv1)"
      echo "Test var 1: " $(tv1)
      ls -lh
  env: {ScanCentral.ClientToken: $(ScanCentral.ClientToken), ScanCentral.SscCiToken: $(ScanCentral.SscCiToken) }